spring:
  data:
    mongodb:
      uri: mongodb://ticket_app:password@localhost:27017/ticketAppDb?authSource=admin&authMechanism=SCRAM-SHA-1

  jpa:
    properties:
      hibernate:
        format_sql: true
        generate_statistics: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        cache:
          use_second_level_cache: true
          use_query_cache: true
          use_structured_entries: true
          region:
            factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory
      javax:
        persistence.sharedCache.mode: ENABLE_SELECTIVE
    show-sql: true

  datasource:
    url: jdbc:postgresql://localhost:5433/ticket_booking
    username: root
    password: root
    driver-class-name: org.postgresql.Driver

logging:
  level:
    org:
      hibernate:
        SQL: debug
        type: trace
    springframework:
      data: debug
    net:
      sf:
        ehcache=debug:
